# Image Jenkins avec ajout zip
#
# VERSION               0.0.1
#

FROM jenkins/jenkins:lts 
MAINTAINER Valentin Brosseau "c4software@gmail.com"

USER root
RUN apt-get update && apt-get install zip
USER jenkins
